#!/bin/bash

echo $ASK_API_KEY

answer=$(curl https://api.openai.com/v1/responses -s \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $ASK_API_KEY" \
	-d '{
		"model": "gpt-5.4",
		"input": [
		{
			"role": "system",
			"content": "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
		},
		{
			"role": "user",
			"content": "Explain the importance of fast language models"
		}
	]
}')

echo $answer
