#!/bin/bash


answer=$(curl https://api.openai.com/v1/responses -s \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $ASK_API_KEY" \
	-d '{
		"model": "gpt-5.4",
		"input": [
		{
			"role": "system",
			"content": "You are a CLI tool. Output plain text only. No yapping. Keep the output concise."
		},
		{
			"role": "user",
			"content": "'"$*"'"
		}
	]
}')

echo $answer | sed -e 's/,/\n/g' | sed -n '/"text": "/,/} ]/p' | sed -e 's/"text": "//' -e's/" } ]//' | awk 'BEGIN {ORS=","} {print $0}' | sed -e 's/\\n/\n/g'

echo -e "\n"
